apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-lbooqjvu
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-lbooqjvu:75c692195f11624fcbddc6284436021b28449b67@sha256:0c9f6b6de7bc3d2e6d796eacf8613444664cc501a51155e84f7c8ac22feeb579
        name: container-image  
